tags:
  - name: Halooo~
get:
  description: Monggo pinarak~
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error